name: test
on:
    pull_request:
        types: [opened, synchronize]
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                go-version: [1.16]
        name: ${{ matrix.os }} test
        steps:
            - uses: actions/checkout@v2
            - name: setup golang
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}
            - name: test
              run: |
                for dockerfile in $(find test -type f -name Dockerfile.'*')
                do
                  name=$(date +%s.%N | sha256sum | cut -f 1 -d ' ' | fold -w 12 | head -n 1)
                  echo "$dockerfile"
                  cat "$dockerfile"
                  docker build -t "$name" -f "$dockerfile" .
                  docker run --rm -v "$(pwd)":/app/src "$name"
                  docker rmi "$name"
                done
