name: test
on:
    pull_request:
        types: [opened, synchronize]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - image: fedora
                      tag: latest
                      command: "dnf -y update && dnf -y upgrade && dnf install -y golang"
                    - image: debian
                      tag: latest
                      command: "export DEBIAN_FRONTEND=noninteractive; apt-get -y update && apt-get upgrade -y && apt-get install -y golang"
                    - image: ubuntu
                      tag: latest
                      command: "export DEBIAN_FRONTEND=noninteractive; apt-get -y update && apt-get upgrade -y && apt-get install -y golang"
                    - image: opensuse/leap
                      tag: latest
                      command: "zypper -n update && zypper -n install go"
                    - image: opensuse/tumbleweed
                      tag: latest
                      command: "zypper -n update && zypper -n install go"
        name: ${{ matrix.image }} test
        steps:
            - uses: actions/checkout@v2
            - name: test
              run: |
                  docker build -t ${{ matrix.image }}-test:latest - << EOF
                  FROM ${{ matrix.image }}:latest
                  WORKDIR /app/src
                  VOLUME /app/src
                  RUN ${{ matrix.command }}
                  ENTRYPOINT ["go", "test", "-v", "./..."]
                  EOF
                  docker run --rm -v "$(pwd)":/app/src ${{ matrix.image }}-test:latest
